In [11]:
# Importing all the packages required for the analysis  
import pandas as pd 
import seaborn as sns
import warnings
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import glob
import os
import plotly.plotly as py
import plotly.graph_objs as go
%matplotlib qt
import mysql.connector

In [12]:
#list all the files required for the analysis
base_dataset=pd.read_excel("ESRD Dataset.xls")

In [13]:
vv=base_dataset.sample(10)
vv.reset_index(inplace=True)
vv.drop("index",axis= 1,inplace=True)
vv

Patient Id  RBCount  SEX  EDUCATION  MARRIAGE  AGE  Eithinicity  \
0       19283   230000    2          2         2   29           -1   
1       10399    50000    1          2         2   22            0   
2       16875   140000    1          2         2   48            0   
3        7014    50000    1          2         1   32            0   
4       28544   120000    2          2         1   35            0   
5       20986   500000    1          1         1   30            0   
6       16095   160000    2          2         2   42            1   
7        8805   140000    2          2         2   29           -1   
8        4538    20000    1          1         2   56            1   
9       13308    50000    1          1         1   33            1   

   Kidney Disfunction  Symptoms  CCIS  Disturbance of Equalibirum   \
0                  -1        -1    -1                           -1   
1                   0         0    -2                           -2   
2                   0         2     2                            2   
3                   0         0     0                            0   
4                   0         0     0                            0   
5                   0         0     0                            0   
6                   2         2     0                            0   
7                  -1        -1    -1                           -1   
8                  -2        -1     0                            0   
9                   2         0     0                            0   

   Blood Flow levels  BMI Index  Shotness of Breath  Uremia Levels  \
0                 -1     1149.0              1149.0         2140.0   
1                 -2    43300.0             43300.0            0.0   
2                  0   124944.0            124944.0       124901.0   
3                  0    35441.0             35441.0        26265.0   
4                  0   113690.0            113690.0       114609.0   
5                  0    75753.0             75753.0        78031.0   
6                  0   152630.0            152630.0        95758.0   
7                 -1      896.0               896.0         2385.0   
8                  2        0.0                 0.0        17901.0   
9                  0    45727.0             45727.0        45515.0   

   Urine Color   ESRD Disease  
0        3313.0             0  
1           0.0             0  
2      129675.0             0  
3       19526.0             0  
4      118232.0             0  
5       78946.0             0  
6       97251.0             1  
7         732.0             0  
8       18217.0             0  
9       45470.0             0

In [14]:


mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="",
  database="cancer"
)

mycursor = mydb.cursor()


In [15]:
for i in range (0,10):
    temp=[]
    for j in vv.columns:
        temp.append(float(vv[j][i]))
    temp=tuple(temp)
    sql = "INSERT INTO head VALUES (%s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s)"
    mycursor.execute(sql, temp)
    mydb.commit()
    print(mycursor.rowcount, "record inserted.")


1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.
1 record inserted.


In [16]:
from IPython.display import HTML
def View(df):
    css = """<style>
    table { border-collapse: collapse; border: 3px solid #eee; }
    table tr th:first-child { background-color: #eeeeee; color: #333; font-weight: bold }
    table thead th { background-color: #eee; color: #000; }
    tr, th, td { border: 1px solid #ccc; border-width: 1px 0 0 1px; border-collapse: collapse;
    padding: 3px; font-family: monospace; font-size: 10px }</style>
    """
    s  = '<script type="text/Javascript">'
    s += 'var win = window.open("", "Title", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=780, height=200, top="+(screen.height-400)+", left="+(screen.width-840));'
    s += 'win.document.body.innerHTML = \'' + (df.to_html() + css).replace("\n",'\\') + '\';'
    s += '</script>'
    return(HTML(s+css))

View(base_dataset.sample(100))

In [17]:
View(base_dataset.sample(100))

In [18]:
base_dataset.head(10)

Patient Id  RBCount  SEX  EDUCATION  MARRIAGE  AGE  Eithinicity  \
0           1    20000    2          2         1   24            2   
1           2   120000    2          2         2   26           -1   
2           3    90000    2          2         2   34            0   
3           4    50000    2          2         1   37            0   
4           5    50000    1          2         1   57           -1   
5           6    50000    1          1         2   37            0   
6           7   500000    1          1         2   29            0   
7           8   100000    2          2         2   23            0   
8           9   140000    2          3         1   28            0   
9          10    20000    1          3         2   35           -2   

   Kidney Disfunction  Symptoms  CCIS  Disturbance of Equalibirum   \
0                   2        -1    -1                           -2   
1                   2         0     0                            0   
2                   0         0     0                            0   
3                   0         0     0                            0   
4                   0        -1     0                            0   
5                   0         0     0                            0   
6                   0         0     0                            0   
7                  -1        -1     0                            0   
8                   0         2     0                            0   
9                  -2        -2    -2                           -1   

   Blood Flow levels  BMI Index  Shotness of Breath  Uremia Levels  \
0                 -2   0.069164            0.069164       0.086723   
1                  2   0.067858            0.067858       0.087817   
2                  0   0.079532            0.079532       0.093789   
3                  0   0.111995            0.111995       0.113407   
4                  0   0.071601            0.071601       0.106020   
5                  0   0.120381            0.120381       0.117974   
6                  0   0.457242            0.457242       0.330672   
7                 -1   0.066581            0.066581       0.086675   
8                  0   0.079598            0.079598       0.092992   
9                 -1   0.066220            0.066220       0.086345   

   Urine Color   ESRD Disease  
0      0.160138             1  
1      0.163220             1  
2      0.173637             0  
3      0.186809             0  
4      0.179863             0  
5      0.178407             0  
6      0.671310             0  
7      0.160346             0  
8      0.171640             0  
9      0.160138             0

In [19]:
# for i in range (0,10):
#     temp=[]
#     for j in vv.columns:
#         temp.append(float(vv[j][i]))
#     temp=tuple(temp)
#     sql = "INSERT INTO head VALUES (%s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s, %s,%s,%s,%s)"
#     mycursor.execute(sql, temp)
#     mydb.commit()
#     print(mycursor.rowcount, "record inserted.")

In [20]:
base_dataset.columns

Index(['Patient Id', 'RBCount', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE',
       'Eithinicity', 'Kidney Disfunction', 'Symptoms', 'CCIS',
       'Disturbance of Equalibirum ', 'Blood Flow levels', 'BMI Index',
       'Shotness of Breath', 'Uremia Levels', 'Urine Color ', 'ESRD Disease'],
      dtype='object')

In [21]:
# check the target distribution

plt.rcParams['figure.figsize'] = (8, 6)

sns.countplot(x='ESRD Disease', data=base_dataset);
plt.savefig("count plot.png")
plt.show()

In [22]:
base_dataset.groupby(by=['SEX', 'ESRD Disease'])['ESRD Disease'].count()

SEX  ESRD Disease
1    0                9015
     1                2873
2    0               14349
     1                3763
Name: ESRD Disease, dtype: int64

In [23]:
pd.crosstab(base_dataset['SEX'], base_dataset['ESRD Disease'])

ESRD Disease      0     1
SEX                      
1              9015  2873
2             14349  3763

In [24]:
# sns.catplot(x='SEX', col='ESRD Disease', kind='count', data=base_dataset);

In [25]:
def nullvalue_function(base_dataset,percentage):
    
    # Checking the null value occurance
    
    print(base_dataset.isna().sum())

    # Printing the shape of the data 
    
    print(base_dataset.shape)
    
    # Converting  into percentage table
    
    null_value_table=pd.DataFrame((base_dataset.isna().sum()/base_dataset.shape[0])*100).sort_values(0,ascending=False )
    
    null_value_table.columns=['null percentage']
    
    # Defining the threashold values 
    
    null_value_table[null_value_table['null percentage']>percentage].index
    
    # Drop the columns that has null values more than threashold 
    base_dataset.drop(null_value_table[null_value_table['null percentage']>30].index,axis=1,inplace=True)
    
    # Replace the null values with median() # continous variables 
    for i in base_dataset.describe().columns:
        base_dataset[i].fillna(base_dataset[i].median(),inplace=True)
    # Replace the null values with mode() #categorical variables
   # for i in base_dataset.describe(include='object').columns:
     #   base_dataset[i].fillna(base_dataset[i].value_counts().index[0],inplace=True)
  
    print(base_dataset.shape)
    
    return base_dataset

In [26]:
base_dataset=nullvalue_function(base_dataset,30)

Patient Id                     0
RBCount                        0
SEX                            0
EDUCATION                      0
MARRIAGE                       0
AGE                            0
Eithinicity                    0
Kidney Disfunction             0
Symptoms                       0
CCIS                           0
Disturbance of Equalibirum     0
Blood Flow levels              0
BMI Index                      0
Shotness of Breath             0
Uremia Levels                  0
Urine Color                    0
ESRD Disease                   0
dtype: int64
(30000, 17)
(30000, 17)


In [27]:
sns.distplot(a=base_dataset['AGE'], color='red');
plt.show

<function matplotlib.pyplot.show(*args, **kw)>

In [28]:
from sklearn import preprocessing

def variables_creation(base_dataset,unique):
    
    cat=base_dataset.describe(include='object').columns
    
    cont=base_dataset.describe().columns
    
    x=[]
    
    for i in base_dataset[cat].columns:
        if len(base_dataset[i].value_counts().index)<unique:
            x.append(i)
    
    dummies_table=pd.get_dummies(base_dataset[x])
    encode_table=base_dataset[x]
    
    le = preprocessing.LabelEncoder()
    lable_encode=[]
    
    for i in encode_table.columns:
        le.fit(encode_table[i])
        le.classes_
        lable_encode.append(le.transform(encode_table[i]))
        
    lable_encode=np.array(lable_encode)
    lable=lable_encode.reshape(base_dataset.shape[0],len(x))
    lable=pd.DataFrame(lable)
    return (lable,dummies_table,cat,cont)

In [29]:
def bivariate_anaysis(base_null_value_treated):
    correlation=[]
    for i in base_null_value_treated.corr().columns:
        for j in base_null_value_treated.corr().columns:
            if i!=j:
                corr=base_null_value_treated[[i,j]].corr().values[0][1]
                d= {
                    'Column name1':i,
                    'Column name2':j,
                    'corr':corr
                   }
                correlation.append(d)

    correlation_table=pd.DataFrame(correlation)
    variables_bivariate=correlation_table[(correlation_table['corr']>0.5) | (correlation_table['corr']<-0.5)]['Column name1'].values
    return variables_bivariate

In [30]:
base_dataset.columns

Index(['Patient Id', 'RBCount', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE',
       'Eithinicity', 'Kidney Disfunction', 'Symptoms', 'CCIS',
       'Disturbance of Equalibirum ', 'Blood Flow levels', 'BMI Index',
       'Shotness of Breath', 'Uremia Levels', 'Urine Color ', 'ESRD Disease'],
      dtype='object')

In [31]:
corr = base_dataset[['RBCount', 'SEX', 'AGE', 'Kidney Disfunction', 'ESRD Disease']].corr()

cmap = sns.diverging_palette(220, 10, as_cmap=True)
sns.heatmap(corr, annot=True, linewidths=1.7, linecolor='white');

In [32]:
def bivariate_analysis():
    for i in bivariate_variables:
        for j in bivariate_variables:
            if i!=j:
                sns.jointplot(base_null_value_treated[i],base_null_value_treated[j])

In [33]:
def univariate_analysis(base_null_value_treated):
    import matplotlib.pyplot as plt
    col=[]
    for i in base_null_value_treated.describe().columns:
        var=base_null_value_treated[i].value_counts().values.var()
        col.append([i,var])
        variance_table=pd.DataFrame(col)
        variance_table[variance_table[1]>100][0].values
    return variance_table[variance_table[1]>100][0].values

        

In [34]:
def outliers(df):
    import numpy as np
    import statistics as sts

    for i in df.describe().columns:
        x=np.array(df[i])
        p=[]
        Q1 = df[i].quantile(0.25)
        Q3 = df[i].quantile(0.75)
        IQR = Q3 - Q1
        LTV= Q1 - (1.5 * IQR)
        UTV= Q3 + (1.5 * IQR)
        for j in x:
            if j <= LTV or j>=UTV:
                p.append(sts.median(x))
            else:
                p.append(j)
        df[i]=p
    return df

#outliers_treated=outliers(base_null_value_treated)

## Baseline Models Creation 

In [35]:
base_dataset.columns

Index(['Patient Id', 'RBCount', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE',
       'Eithinicity', 'Kidney Disfunction', 'Symptoms', 'CCIS',
       'Disturbance of Equalibirum ', 'Blood Flow levels', 'BMI Index',
       'Shotness of Breath', 'Uremia Levels', 'Urine Color ', 'ESRD Disease'],
      dtype='object')

In [36]:
base_dataset=base_dataset[base_dataset.describe().columns]

In [37]:
base_dataset.head()

Patient Id  RBCount  SEX  EDUCATION  MARRIAGE  AGE  Eithinicity  \
0           1    20000    2          2         1   24            2   
1           2   120000    2          2         2   26           -1   
2           3    90000    2          2         2   34            0   
3           4    50000    2          2         1   37            0   
4           5    50000    1          2         1   57           -1   

   Kidney Disfunction  Symptoms  CCIS  Disturbance of Equalibirum   \
0                   2        -1    -1                           -2   
1                   2         0     0                            0   
2                   0         0     0                            0   
3                   0         0     0                            0   
4                   0        -1     0                            0   

   Blood Flow levels  BMI Index  Shotness of Breath  Uremia Levels  \
0                 -2   0.069164            0.069164       0.086723   
1                  2   0.067858            0.067858       0.087817   
2                  0   0.079532            0.079532       0.093789   
3                  0   0.111995            0.111995       0.113407   
4                  0   0.071601            0.071601       0.106020   

   Urine Color   ESRD Disease  
0      0.160138             1  
1      0.163220             1  
2      0.173637             0  
3      0.186809             0  
4      0.179863             0

In [38]:
base_dataset.describe().T

count           mean            std       min  \
Patient Id                   30000.0   15000.500000    8660.398374       1.0   
RBCount                      30000.0  167484.322667  129747.661567   10000.0   
SEX                          30000.0       1.603733       0.489129       1.0   
EDUCATION                    30000.0       1.853133       0.790349       0.0   
MARRIAGE                     30000.0       1.551867       0.521970       0.0   
AGE                          30000.0      35.485500       9.217904      21.0   
Eithinicity                  30000.0      -0.016700       1.123802      -2.0   
Kidney Disfunction           30000.0      -0.133767       1.197186      -2.0   
Symptoms                     30000.0      -0.166200       1.196868      -2.0   
CCIS                         30000.0      -0.220667       1.169139      -2.0   
Disturbance of Equalibirum   30000.0      -0.266200       1.133187      -2.0   
Blood Flow levels            30000.0      -0.291100       1.149988      -2.0   
BMI Index                    30000.0   48803.894853   70987.619598  -69777.0   
Shotness of Breath           30000.0   48803.894853   70987.619598  -69777.0   
Uremia Levels                30000.0   46661.338407   69160.620872 -157264.0   
Urine Color                  30000.0   42922.723622   63999.660769 -170000.0   
ESRD Disease                 30000.0       0.221200       0.415062       0.0   

                                  25%       50%        75%        max  
Patient Id                    7500.75   15000.5   22500.25    30000.0  
RBCount                      50000.00  140000.0  240000.00  1000000.0  
SEX                              1.00       2.0       2.00        2.0  
EDUCATION                        1.00       2.0       2.00        6.0  
MARRIAGE                         1.00       2.0       2.00        3.0  
AGE                             28.00      34.0      41.00       79.0  
Eithinicity                     -1.00       0.0       0.00        8.0  
Kidney Disfunction              -1.00       0.0       0.00        8.0  
Symptoms                        -1.00       0.0       0.00        8.0  
CCIS                            -1.00       0.0       0.00        8.0  
Disturbance of Equalibirum      -1.00       0.0       0.00        8.0  
Blood Flow levels               -1.00       0.0       0.00        8.0  
BMI Index                     2749.75   20739.5   63343.25   983931.0  
Shotness of Breath            2749.75   20739.5   63343.25   983931.0  
Uremia Levels                 2482.75   19871.0   59724.00  1664089.0  
Urine Color                   2130.00   18864.0   53852.50   891586.0  
ESRD Disease                     0.00       0.0       0.00        1.0

In [39]:
# plotCorrelationMatrix(base_dataset, 8)

## Logistic Regression

In [40]:
base_dataset=base_dataset[base_dataset.describe().columns]
y=base_dataset['ESRD Disease']
X=base_dataset.drop(['ESRD Disease',"Patient Id"],axis=1)

In [41]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
import numpy as np

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning:

numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.



In [42]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    '''
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    if train:
        '''
        training performance
        '''
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))    
        

In [43]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
print_score(lr, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.7792

Classification Report: 
              precision    recall  f1-score   support

          0       0.78      1.00      0.88     16364
          1       0.00      0.00      0.00      4636

avg / total       0.61      0.78      0.68     21000


Confusion Matrix: 
 [[16364     0]
 [ 4636     0]]

Average Accuracy: 	 0.7792
Accuracy SD: 		 0.0002


In [45]:
X_train.head().shape

(5, 15)

In [46]:
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.7778

Classification Report: 
              precision    recall  f1-score   support

          0       0.78      1.00      0.88      7000
          1       0.00      0.00      0.00      2000

avg / total       0.60      0.78      0.68      9000


Confusion Matrix: 
 [[7000    0]
 [2000    0]]



In [47]:
from sklearn.ensemble import RandomForestClassifier
lr=RandomForestClassifier()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
print_score(lr, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9779

Classification Report: 
              precision    recall  f1-score   support

          0       0.97      1.00      0.99     16364
          1       0.99      0.91      0.95      4636

avg / total       0.98      0.98      0.98     21000


Confusion Matrix: 
 [[16337    27]
 [  438  4198]]

Average Accuracy: 	 0.8049
Accuracy SD: 		 0.0045


In [49]:
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.8023

Classification Report: 
              precision    recall  f1-score   support

          0       0.83      0.94      0.88      7000
          1       0.60      0.33      0.43      2000

avg / total       0.78      0.80      0.78      9000


Confusion Matrix: 
 [[6558  442]
 [1337  663]]



In [50]:
from sklearn.tree import DecisionTreeClassifier
lr=DecisionTreeClassifier()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
print_score(lr, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9994

Classification Report: 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00     16364
          1       1.00      1.00      1.00      4636

avg / total       1.00      1.00      1.00     21000


Confusion Matrix: 
 [[16363     1]
 [   11  4625]]

Average Accuracy: 	 0.7232
Accuracy SD: 		 0.0081


In [52]:
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.7284

Classification Report: 
              precision    recall  f1-score   support

          0       0.83      0.82      0.82      7000
          1       0.40      0.42      0.41      2000

avg / total       0.74      0.73      0.73      9000


Confusion Matrix: 
 [[5710 1290]
 [1154  846]]



In [53]:
from sklearn.naive_bayes import BernoulliNB
lr=BernoulliNB()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
print_score(lr, X_train, y_train, X_test, y_test, train=True)
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.7968

Classification Report: 
              precision    recall  f1-score   support

          0       0.85      0.90      0.87     16364
          1       0.55      0.45      0.49      4636

avg / total       0.78      0.80      0.79     21000


Confusion Matrix: 
 [[14646  1718]
 [ 2549  2087]]

Average Accuracy: 	 0.7957
Accuracy SD: 		 0.0045
Test Result:

accuracy score: 0.7853

Classification Report: 
              precision    recall  f1-score   support

          0       0.84      0.89      0.87      7000
          1       0.52      0.41      0.46      2000

avg / total       0.77      0.79      0.78      9000


Confusion Matrix: 
 [[6238  762]
 [1170  830]]



In [55]:
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.7853

Classification Report: 
              precision    recall  f1-score   support

          0       0.84      0.89      0.87      7000
          1       0.52      0.41      0.46      2000

avg / total       0.77      0.79      0.78      9000


Confusion Matrix: 
 [[6238  762]
 [1170  830]]



In [56]:
from sklearn.neighbors import KNeighborsClassifier
lr=KNeighborsClassifier()
lr.fit(X_train,y_train)
lr.predict(X_test)
print_score(lr, X_train, y_train, X_test, y_test, train=True)
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.8115

Classification Report: 
              precision    recall  f1-score   support

          0       0.83      0.95      0.89     16364
          1       0.65      0.32      0.43      4636

avg / total       0.79      0.81      0.79     21000


Confusion Matrix: 
 [[15573   791]
 [ 3168  1468]]

Average Accuracy: 	 0.7446
Accuracy SD: 		 0.0058
Test Result:

accuracy score: 0.7452

Classification Report: 
              precision    recall  f1-score   support

          0       0.79      0.91      0.85      7000
          1       0.35      0.17      0.23      2000

avg / total       0.70      0.75      0.71      9000


Confusion Matrix: 
 [[6360  640]
 [1653  347]]



In [57]:
import xgboost as xgb
lr = xgb.XGBClassifier()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print_score(lr, X_train, y_train, X_test, y_test, train=True)
print_score(lr, X_train, y_train, X_test, y_test, train=False)

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.



Train Result:

accuracy score: 0.8263



C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.



Classification Report: 
              precision    recall  f1-score   support

          0       0.84      0.95      0.90     16364
          1       0.70      0.38      0.49      4636

avg / total       0.81      0.83      0.81     21000


Confusion Matrix: 
 [[15604   760]
 [ 2887  1749]]



C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in a

Average Accuracy: 	 0.8232
Accuracy SD: 		 0.0055
Test Result:

accuracy score: 0.8202

Classification Report: 
              precision    recall  f1-score   support

          0       0.84      0.95      0.89      7000
          1       0.68      0.36      0.47      2000

avg / total       0.80      0.82      0.80      9000


Confusion Matrix: 
 [[6660  340]
 [1278  722]]



C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.



In [58]:
from sklearn.model_selection import cross_val_score  
all_accuracies_GaussianNB = cross_val_score(estimator=DecisionTreeClassifier(), X=X_train, y=y_train, cv=10)  
all_accuracies_GaussianNB=pd.DataFrame(all_accuracies_GaussianNB)
all_accuracies_GaussianNB.plot()

In [59]:
from sklearn.model_selection import cross_val_score  
all_accuracies_GaussianNB = cross_val_score(estimator=RandomForestClassifier(), X=X_train, y=y_train, cv=10)  
all_accuracies_GaussianNB=pd.DataFrame(all_accuracies_GaussianNB)
all_accuracies_GaussianNB.plot()

In [60]:
from sklearn.model_selection import cross_val_score  
from sklearn.naive_bayes import GaussianNB
all_accuracies_GaussianNB = cross_val_score(estimator=GaussianNB(), X=X_train, y=y_train, cv=10)  
all_accuracies_GaussianNB=pd.DataFrame(all_accuracies_GaussianNB)
all_accuracies_GaussianNB.plot()


In [61]:
from sklearn.model_selection import cross_val_score  
all_accuracies_GaussianNB = cross_val_score(estimator=GaussianNB(), X=X_train, y=y_train, cv=10)  
all_accuracies_GaussianNB=pd.DataFrame(all_accuracies_GaussianNB)
all_accuracies_GaussianNB.plot()

In [62]:
from sklearn.model_selection import cross_val_score  
all_accuracies_GaussianNB = cross_val_score(estimator=KNeighborsClassifier(), X=X_train, y=y_train, cv=10)  
all_accuracies_GaussianNB=pd.DataFrame(all_accuracies_GaussianNB)
all_accuracies_GaussianNB.plot()

In [65]:
X_test.head().T

19273     1386      15995     28643     17250
RBCount                      150000.0  360000.0  140000.0  460000.0  100000.0
SEX                               2.0       1.0       2.0       2.0       2.0
EDUCATION                         2.0       1.0       1.0       1.0       2.0
MARRIAGE                          2.0       2.0       2.0       2.0       1.0
AGE                              32.0      36.0      33.0      35.0      37.0
Eithinicity                       0.0      -1.0       0.0       1.0       0.0
Kidney Disfunction                0.0      -1.0       0.0      -1.0       0.0
Symptoms                          0.0      -1.0       0.0      -1.0       0.0
CCIS                              0.0       0.0       0.0       0.0       0.0
Disturbance of Equalibirum        0.0       0.0       0.0       0.0       0.0
Blood Flow levels                 0.0       0.0       0.0       0.0       0.0
BMI Index                     32136.0  208305.0   88906.0     693.0  101587.0
Shotness of Breath            32136.0  208305.0   88906.0     693.0  101587.0
Uremia Levels                 28151.0   68214.0   88736.0  224526.0  100095.0
Urine Color                   27697.0  168014.0   91287.0  227242.0   98569.0

In [66]:
X_test.head().columns

Index(['RBCount', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'Eithinicity',
       'Kidney Disfunction', 'Symptoms', 'CCIS', 'Disturbance of Equalibirum ',
       'Blood Flow levels', 'BMI Index', 'Shotness of Breath', 'Uremia Levels',
       'Urine Color '],
      dtype='object')

In [68]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="",
  database="cancer"
)
mycursor = mydb.cursor()
mycursor.execute("SELECT * FROM prediction")
myresult = mycursor.fetchall()
q=[]
for x in myresult:
    for i in x:
        if i is not None:
            #print(i)
            q.append(float(i))
                
        else:
            #print(i)
            q.append(i)
# q
q=pd.DataFrame(q)
q=q.T
q=q.iloc[:,:-1]
q.columns=['RBCount', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'Eithinicity',
       'Kidney Disfunction', 'Symptoms', 'CCIS', 'Disturbance of Equalibirum ',
       'Blood Flow levels', 'BMI Index', 'Shotness of Breath', 'Uremia Levels',
       'Urine Color ']

e=lr.predict(q)
sql = "update prediction set ESRD_Disease = %s"
val= str(e[0])
mycursor.execute(sql, (val,))
mydb.commit()

C:\Users\Subh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning:

The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.

